# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            FloatingMuseum
tagline:          'Want to be a better guy'
description:      'A normal Android developer.'
url:		  http://floatingmuseum.github.io

author:
  name:           'SooHu'
  url:            https://github.com/SooHu

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : Floatingmuseum
