# Dependencies
markdown:         kramdown
highlighter:      rouge

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            FloatingMuseum
tagline:          'Want to be a better guy'
description:      'A normal Android developer.'
url:		  http://floatingmuseum.github.io

author:
  name:           'FloatingMuseum'
  url:            http://floatingmuseum.github.io

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : floatingmuseum
